"""empty message

Revision ID: 6cbd0f5e0dd3
Revises: 15017325bcdc
Create Date: 2026-05-21 08:13:44.370570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbd0f5e0dd3'
down_revision: Union[str, Sequence[str], None] = '15017325bcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_account_email_key'), 'users_account', type_='unique')
    op.drop_column('users_account', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_account', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_account_email_key'), 'users_account', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
