"""empty message

Revision ID: 9ee01188e71a
Revises: 94331e8b6e6b
Create Date: 2026-05-26 18:38:55.384147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision: str = '9ee01188e71a'
down_revision: Union[str, Sequence[str], None] = '94331e8b6e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barter_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'COMPLETED', 'CANCELED', name='dealstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=datetime.timezone.utc), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=datetime.timezone.utc), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=datetime.timezone.utc), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users_account.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['users_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('offered_title', sa.String(length=150), nullable=False),
    sa.Column('offered_description', sa.Text(), nullable=False),
    sa.Column('offered_item_category', sa.Enum('ELECTRONICS', 'CLOTHING', 'FURNITURE', 'BOOKS', 'VEHICLES', 'OTHER', name='itemcategory'), nullable=False),
    sa.Column('desired_offer', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXCHANGED', 'DELETED', name='barterstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barter_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barter_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barter_id'], ['barters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barter_media')
    op.drop_table('barters')
    op.drop_table('barter_deals')
    # ### end Alembic commands ###
